packages:
  - packages/**

catalog:
  '@arethetypeswrong/cli': ^0.17.3
  '@ariakit/react': ^0.3.6
  '@ariakit/react-core': ^0.3.6
  '@heroicons/react': ^2.0.17
  '@inquirer/core': ^5.1.1
  '@inquirer/prompts': ^3.3.0
  '@ipld/car': ^5.4.0
  '@ipld/dag-cbor': ^9.0.6
  '@ipld/dag-json': ^10.2.3
  '@ipld/dag-ucan': ^3.4.5
  '@ipld/schema': ^6.0.6
  '@ipld/unixfs': ^3.0.0
  '@nx/js': 20.3.2
  '@playwright/test': ^1.29.2
  '@scure/bip39': ^1.2.1
  '@storacha/one-webcrypto': ^1.0.1
  '@tailwindcss/postcss': ^4.0.3
  '@testing-library/react': ^14.1.2
  '@testing-library/user-event': ^14.5.1
  '@types/inquirer': ^9.0.4
  '@types/react': ^18.2.37
  '@types/react-dom': ^18.2.15
  '@types/sinon': ^10.0.19
  '@types/update-notifier': ^6.0.5
  '@types/varint': ^6.0.1
  '@types/ws': ^8.5.4
  '@typescript-eslint/eslint-plugin': 8.26.1
  '@typescript-eslint/parser': 8.26.1
  '@ucanto/client': ^9.0.1
  '@ucanto/core': ^10.4.0
  '@ucanto/interface': '^10.3.0'
  '@ucanto/principal': '^9.0.2'
  '@ucanto/server': '^10.2.0'
  '@ucanto/transport': ^9.2.0
  '@ucanto/validator': ^9.1.0
  '@vitejs/plugin-react': ^4.2.0
  '@web-std/blob': ^3.0.5
  '@web3-storage/did-mailto': ^2.1.0
  '@web3-storage/sigv4': ^1.0.2
  '@web3-storage/upload-api': ^19.0.0
  '@web3-storage/content-claims': ^5.2.1
  '@web3-storage/data-segment': ^5.3.0
  ansi-escapes: ^6.2.0
  ariakit-utils: 0.17.0-next.27
  ariakit-react-utils: 0.17.0-next.27
  assert: ^2.0.0
  autoprefixer: ^10.4.13
  bigint-mod-arith: ^3.1.2
  blockstore-core: ^3.0.0
  carstream: ^2.1.0
  chalk: ^5.3.0
  conf: 11.0.2
  crypto-random-string: ^5.0.0
  depcheck: ^1.4.3
  eslint: ^8.53.0
  eslint-plugin-jsdoc: ^50.6.3
  eslint-plugin-react: ^7.33.2
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-react-refresh: ^0.4.4
  fake-indexeddb: ^5.0.1
  files-from-path: ^1.0.4
  fr32-sha2-256-trunc254-padded-binary-tree-multihash: ^3.3.0
  happy-dom: ^12.10.3
  hd-scripts: ^4.1.0
  hundreds: ^0.0.9
  ipfs-unixfs-exporter: ^10.0.0
  ipfs-utils: ^9.0.14
  is-subset: ^0.1.1
  jsdom: ^23.0.1
  lint-staged: ^13.2.0
  multiformats: ^13.3.3
  next: ^13.5.4
  npm-run-all: ^4.1.5
  nx: 20.3.2
  open: ^9.1.0
  ora: ^7.0.1
  p-defer: ^4.0.0
  p-map: ^6.0.0
  p-retry: ^5.1.2
  p-wait-for: ^5.0.2
  playwright-test: ^12.3.4
  postcss: ^8.4.21
  pretty-tree: ^1.0.0
  react: ^18.2.0
  react-dom: ^18.2.0
  s-ago: ^2.2.0
  sade: ^1.8.1
  serve: ^14.1.2
  sinon: ^15.0.3
  swr: ^2.2.4
  tailwindcss: ^3.2.4
  typescript: ^5.8.3
  update-notifier: ^7.0.0
  varint: ^6.0.0
  vite: ^5.0.0
  vitest: ^1.0.1
  watch: ^1.0.2
