export const DEFAULT_STOP_ON_ERROR = true
export const DEFAULT_PULL_RETRIES = 3
export const DEFAULT_MAX_COMMIT_RETRIES = 3
export const DEFAULT_COMMIT_RETRY_TIMEOUT = 30_000
export const DEFAULT_PULL_BATCH_SIZE = 20
export const DEFAULT_PULL_CONCURRENCY = 4
export const DEFAULT_COMMIT_CONCURRENCY = 4
export const DEFAULT_SHARD_LIST_CONCURRENCY = 4
export const DEFAULT_CARPARK_CONCURRENCY = 8
export const DEFAULT_STORE_CONCURRENCY = 10
export const DEFAULT_STORE_FETCH_RETRIES = 2
export const DEFAULT_STORE_OPERATION_RETRIES = 2
export const MAX_CREATE_DATASET_COMMIT_BATCH_PIECES = 0
export const MAX_ADD_PIECES_COMMIT_BATCH_PIECES = 0
export const MAX_COMMIT_EXTRADATA_BYTES = 8_192

export const PRIMARY_COPY_INDEX = 0
export const SECONDARY_COPY_INDEX = 1
