name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write  # Required for OIDC

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install
        uses: pnpm/action-setup@v4
      - name: Setup
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - name: Install npm package dependencies
        run: pnpm install --frozen-lockfile          
      - name: Update Release PR or Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          MAIN_BRANCH_NAME: ${{ github.event.repository.default_branch }}
          COMMIT_BEFORE: ${{ github.event.before }}
          RELEASE_BRANCH_NAME: release
          LOGLEVEL: ${{ runner.debug && 'debug' || '' }}
        run: pnpm tsx ./.github/release/release.mts
